---
title: "Vac_ariadna"
author: "Anton Zhelonkin"
date: "23 02 2022"
output: html_document
---
```{r}
ariadna_base <- read.csv2("/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna_all.csv")
```
```{r}
str(ariadna_base)
```
```{r}
ariadna_base$birth_date <- as.Date(ariadna_base$birth_date)
ariadna_base$in_date <- as.Date(ariadna_base$in_date)
ariadna_base$out_date <- as.Date(ariadna_base$out_date)
```

```{r}
str(ariadna_base)
```
Cабсет 2021 года


```{r}
ariadna21 <- subset(ariadna_base, format(ariadna_base$in_date,"%Y")==2021)
ariadna20 <- subset(ariadna_base, format(ariadna_base$in_date,"%Y")==2020)
ariadna19 <- subset(ariadna_base, format(ariadna_base$in_date,"%Y")==2019)

write.csv2(ariadna21, "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna21.csv", row.names = FALSE)
write.csv2(ariadna20, "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna20.csv", row.names = FALSE)
write.csv2(ariadna19, "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna19.csv", row.names = FALSE)
```

## 2019 год
Всего случаев по базе
```{r}
total19 <- length(ariadna19$num)
total19
```

Вакинированные
```{r}
ariadna19[grep("вакцин", ariadna19$history), ]
```
```{r}
ariadna19[grep("вакцин", ariadna19$history), ]$out_ds
```


Доля
```{r}
1 / total19 * 100
```


## 2020 год
Всего случаев
```{r}
total20 <- length(ariadna20$num)
total20
```
Вакцинированные
```{r}
ariadna20[grep("вакцин", ariadna20$history), ]
```
Диагноз вакцинированных
```{r}
ariadna20[grep("вакцин", ariadna20$history), ]$out_ds
```



```{r}
3 / total20 * 100
```


## 2021
Всего случаев
```{r}
total21 <- length(ariadna21$num)
total21
```
Вакцинированные
```{r}
ariadna21[grep("вакцин", ariadna21$history), ]
```

```{r}
49 / total21 * 100
```
```{r}
ariadna21[grep("вакцин", ariadna21$history), ]$out_ds
```

```{r}
table(ariadna21[grep("вакцин", ariadna21$history), ]$out_ds)
```
Запишу отдельную таблицу с вакцинированными в 2021
```{r}
ariadna21_vac <- ariadna21[grep("вакцин", ariadna21$history), ]
write.csv2(ariadna21_vac, "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna21_vac.csv", row.names = FALSE)
```




```{r}
marova <- ariadna21[grep("спутник", ariadna21$history), ]
write.csv2(marova, "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/marova.csv", row.names = FALSE)
```


## Сводная статистика
```{r}
year <- c(2019, 2020, 2021)
cases_vac <- c(1, 3, 49)
cases_total <- c(3023, 2181, 3058)
cases_minus <- c(3022, 2178, 3009)
vac <- data.frame(year, cases_vac, cases_total, cases_minus)

norm <- replicate("N", 3022)
```

```{r}
library(ggplot2)
vaccs <- read.csv2("/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/ariadna/ariadna21_vac_eyeviewed.csv")
```


```{r}
unique(vaccs$out_ds)
ds_names <- c("L20.0 Атопический дерматит", "L20.8/L30.3 Экзема/микробная",
              "L27.0-9 Токсикодермия", "L27.0-9 Токсикодермия",
              "L28.2 Пруриго", "L20.8/L30.3 Экзема/микробная",
              "L40.0-8 Псориаз", "L40.0-8 Псориаз",
              "L41.3 Парапсориаз мелкобляшечный", "L43.2-8 КПЛ", "L43.2-8 КПЛ",
              "L43.2-8 КПЛ", "L50.9 Крапивница",
              "L92.0 Гранулематозы", "L94.0 Морфеа",
              "L95.0-8 Васкулит", "L95.0-8 Васкулит")

vaccs$out_ds <- factor(vaccs$out_ds, 
                       levels = c("L20.0", "L20.8",
                                  "L27.0", "L27.9",
                                  "L28.2", "L30.3",
                                  "L40.0", "L40.8",
                                  "L41.3", "L43.2", "L43.3",
                                  "L43.8", "L50.9",
                                  "L92.0", "L94.0",
                                  "L95.0", "L95.8"),
                       labels = ds_names
                       )
vaccs$postvac <- factor(vaccs$postvac, levels = c("manifest", "flare"),
                        labels = c("Впервые", "Обострение"))
```
```{r}
table(vaccs$out_ds, vaccs$postvac)
```


```{r}
ggMMplot <- function(var1, var2){
  require(ggplot2)
  levVar1 <- length(levels(var1))
  levVar2 <- length(levels(var2))

  jointTable <- prop.table(table(var1, var2))
  plotData <- as.data.frame(jointTable)
  plotData$marginVar1 <- prop.table(table(var1))
  plotData$var2Height <- plotData$Freq / plotData$marginVar1
  plotData$var1Center <- c(0, cumsum(plotData$marginVar1)[1:levVar1 -1]) +
    plotData$marginVar1 / 2

  ggplot(plotData, aes(var1Center, var2Height)) +
    theme_bw()+
    scale_fill_brewer(type = "qual", palette = "Set3")+
    geom_bar(stat = "identity", aes(width = marginVar1, fill = var2), col = "Black") +
    geom_text(aes(label = as.character(var1), x = var1Center, y = 1.05)) +
    guides(fill=guide_legend(title="МКБ Нозологии"))+
    labs(x = NULL, y = NULL)
  }

p <- ggMMplot(vaccs$postvac, vaccs$out_ds)
p
```
```{r}
ggsave(filename = "/Users/Tony/Desktop/R/Projects/Covid_vac_dotplot/contingency.png", plot = p, dpi = 400,
       height = 7, width = 10)
```



```{r}
ggplot(data = vaccs) +
  geom_mosaic(aes(x = postvac, fill=out_ds)) + 
  labs(title='f(rude_to_recline)')
```

```{r}
ggplot(vaccs, aes(x = postvac, fill = out_ds))+
  geom_bar()+
  theme_bw()
```


```{r}
ggplot(vaccs, aes(y = out_ds, fill = out_ds))+
  geom_bar()+
  theme_bw()+
  facet_grid(~postvac)
```

